# Generated by Django 3.2.13 on 2022-06-28 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ecosystem",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Organization ID from GitHub",
                    ),
                ),
                ("installation_id", models.PositiveBigIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstalledOrganization",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Organization ID from GitHub",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("installation_id", models.PositiveBigIntegerField()),
                (
                    "organization_login",
                    models.SlugField(
                        help_text="Like a GitHub username, GitHub organizations also have a unique GitHub username. You can identify this from the URL of the organization's GitHub profile such as `https://github.com/The-Ur` where The-Ur is the slug.",
                        max_length=39,
                        verbose_name="Organization slug/username",
                    ),
                ),
                ("sender_id", models.PositiveBigIntegerField()),
                ("is_organization", models.BooleanField(default=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Deleted"),
                            (2, "Suspend"),
                            (3, "Unsuspend"),
                        ]
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="GitHub Webhook Payload"
                    ),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="EcosystemApplication",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ecosystem.installedorganization",
                        verbose_name="Organization ID from GitHub",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "organization_login",
                    models.SlugField(
                        help_text="Like a GitHub username, GitHub organizations also have a unique GitHub username. You can identify this from the URL of the organization's GitHub profile such as `https://github.com/The-Ur` where The-Ur is the slug.",
                        max_length=39,
                        verbose_name="Organization slug/username",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Why should this ecosystem exist?",
                        verbose_name="Reason to join",
                    ),
                ),
                (
                    "admin_reason",
                    models.TextField(
                        help_text="(Admin only) Reasons to accept include a vibrant community or enough dedicated packages for a community to organize around. Rejection reasons can range from duplicate to too niche.",
                        verbose_name="Accept/Rejection Reason",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
