# Generated by Django 3.2.13 on 2022-07-10 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecosystem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Repository ID from GitHub",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(max_length=30, verbose_name="Repository node ID"),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Repository name without organization name",
                        max_length=255,
                        verbose_name="Repository slug",
                    ),
                ),
                ("is_package", models.BooleanField(default=False)),
                (
                    "ecosystem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecosystem.ecosystem",
                    ),
                ),
            ],
        ),
    ]
